### ISSUE TITLE
Premium | Multiple users can sign in per Premium account

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#12] opened 2023-01-09 16:19 UTC
Ops Feature Request #1 | Multi-user sign per Premium account
Multiply users can sign in per Premium account (for organizations that need to manage multiple endpoints w/ multiple devs under one account).

Ancillary Components To include:
1) Any User can Top Up a Premium Account - identifiable by Wallet Address (which controls the acc)

**Comment by yenicelik** [comment] 2023-03-25 21:22
@LlamaMB Just to specify the features here further for implementation:

- There is a "primary" account, this is someone with an (ethereum) wallet
- There are "secondary" accounts, these are also users with (ethereum) wallets, but they all are "subaccounts" of the primary account
- secondary users cannot have their own account, they can only be subaccounts (this constraint would make implementation easier, else some appropriate design may be needed)
- any request that the secondary user makes, the primary user is charged for. 
- secondary users can top-up balance (through their own wallets), but only the "primary" account will receive the credits.

- should the secondary user be able to withdraw the balance? or would the withdrawed balance be received by the primary account only?

**Comment by yenicelik** [comment] 2023-03-28 12:14
(1) yes
(2) yes, primary determines accepted wallet addresses
 -> limited access (cannot withdraw funds + delete api / rpc keys) ; nothing destructive
(3) gotta use a new wallet indeed (secondary account cannot have their own primary account)
(4) yes
(5) anyone can top up (anyone can deposit, but cannot withdraw)
(6) nope, just primary has email
(7) cannot withdraw

**Comment by yenicelik** [comment] 2023-04-12 14:57
Implementation details: 

To create the secondary user, will have to create the following changes: 

TODO:s
- add to table `secondary_user` (1) the column `secondary_user_to` which marks who the primary user is and (2) the column 'confirmed'.
- add some endpoints to register a secondary user (the primary user does this, the secondary user confirms this). otherwise the secondary user can be forcefully added / blocked. specifically, one endpoint for the owner, and then another special login endpoint for a logged-in user to validate it. 
- login endpoint: each secondary user has their own bearer token & RPC key. 

TODOs billing: 
- for billing, we lookup who the primary account is, and subtract items from that account (affects stasts/mod.rs)
- when depositing tokens, the tokens of the secondary user are accounted towards the primary user (affects endpoint POST user/balance/:tx_hash endpoint)
- if the billing runs low on funds, the primary user is notified / downgraded
- on each RPC call, we always translate the balance to the primary user. we check + rate-limit accordingly. I might need Bryan's help on this (specifically for the rate-limiting, especially if we use a user-sharded haproxy policy)

No changes needed:
- secondary users cannot withdraw (thats not implemented rn anyways)
- we don't have to change the login, as the user-table will mark a user as a secondary user (this address will have an entry in secondary-user)
- let's not touch the login flow if not needed
- a secondary user cannot be added to multiple projects
- one user can have two log-ins at the same time so that's fine 

disclaimer: 
- One secondary user can be assigned to at most one primary user. A secondary user cannot have multiple projects

**Comment by yenicelik** [comment] 2023-04-13 14:09
legacy TODOs (which are not happening anymore): 
- when depositing tokens, the tokens of the secondary user are accounted towards the primary user (affects endpoint POST user/balance/:tx_hash endpoint)
- if the billing runs low on funds, the primary user is notified / downgraded
- on each RPC call, we always translate the balance to the primary user. we check + rate-limit accordingly. I might need Bryan's help on this (specifically for the rate-limiting, especially if we use a user-sharded haproxy policy) (alternatively we can also just use the role of the user, which will be the same as the primary user; and the role will be updated in stats/mod.rs)

**Comment by yenicelik** [comment] 2023-06-11 16:08
I will close this issue because this is already implemented, and now it's about finding edge cases that do/dont work (or are not defined by product specifications)

**Closed by yenicelik** 2023-06-11 16:08 UTC
