### ISSUE TITLE
LlamaNodes Premium Low Funds Email Notification System

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#38] opened 2023-03-06 13:20 UTC
LlamaNodes Premium Low Funds Email Notification System 

**Scope:** Implement an automated email notification system via email collection, user balance, and SendGrid API. 
**Objective:** Automatically warn Premium users they are low on funds “out of funds” by email which is triggered via SendGrid API.

**Elements**
- Threshold: Email is triggered when the account goes below the $50.00 USD threshold (if they’ve deposited more than $100.00 USD). 
- SendGrid API Integration Guide: https://app.sendgrid.com/guide/integrate
- Email storage: “Emails are stored in the web3-proxy database” 
- Email templates and SendGrid log-in can be accessed by LlamaMB

**Comment by WyseNynja** [comment] 2023-07-06 23:09
dupe of #163

**Closed by WyseNynja** 2023-07-06 23:09 UTC
